const SORTING_SORT_PARAMETER = "sort";
const SORTING_ASCENDING_PARAMETER = "asc";
const SORTING_DESCENDING_PARAMETER = "desc";

const PAGINATION_PAGE_PARAMETER = "page";
const PAGINATION_SIZE_PARAMETER = "size";

const FILTERING_EQUAL_OPERATOR = "eq";
const FILTERING_LIKE_OPERATOR = "lk";
const FILTERING_INEQUALITY_OPERATOR = "neq";
const FILTERING_GREATER_THAN_OPERATOR = "gt";
const FILTERING_GREATER_THAN_OR_EQUAL_TO_OPERATOR = "gte";
const FILTERING_LESS_THAN_OPERATOR = "lt";
const FILTERING_LESS_THAN_OR_EQUAL_TO_OPERATOR = "lte";

const AMPERSAND = "&";
const EQUALS = "=";
const QUESTION_MARK = "?";
const COLON_OPERATOR = ":";
const COMMA = ",";

module.exports = {
	SORTING_SORT_PARAMETER,
	SORTING_ASCENDING_PARAMETER, 
	SORTING_DESCENDING_PARAMETER, 
	SORTING_DESCENDING_PARAMETER,
	PAGINATION_PAGE_PARAMETER,
	PAGINATION_SIZE_PARAMETER,
	FILTERING_EQUAL_OPERATOR,
	FILTERING_LIKE_OPERATOR,
    FILTERING_INEQUALITY_OPERATOR,
    FILTERING_GREATER_THAN_OPERATOR,
	FILTERING_GREATER_THAN_OR_EQUAL_TO_OPERATOR,
	FILTERING_GREATER_THAN_OR_EQUAL_TO_OPERATOR,
    FILTERING_LESS_THAN_OPERATOR,
    FILTERING_LESS_THAN_OR_EQUAL_TO_OPERATOR,
    AMPERSAND,
    EQUALS,
    QUESTION_MARK,
    COLON_OPERATOR,
    COMMA
};